---
title: "8: Run Atlantic salmon model"
subtitle: "Local to global salmon aquaculture waste modelling"
author:
  - "Tormey Reimer"
date: last-modified
format: html
editor: source
---

[← Previous: How many runs per farm?](07_how_many_runs_per_farm.qmd)

# Overview {#sec-overview}

This document runs the aquaculture model for Atlantic salmon farms.

```{r setup}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(arrow)
library(sf)
library(terra)
library(furrr)
library(future)
library(progressr)
library(fs)
library(conflicted)
library(readxl)
library(units)
library(qs)
library(here)
library(targets)
library(lme4)
library(MuMIn)
conflicted::conflicts_prefer(dplyr::filter(), dplyr::select(), .quiet = T)

here("src") %>% 
  list.files(pattern = "\\.R$", full.names = TRUE) %>% 
  str_subset("map", negate = T) %>% 
  str_subset("pipeline", negate = T) %>% 
  walk(source)
```

# Run the farms pipeline {#sec-run-pipeline}

The following code runs the main pipeline.

```{r run-farms-pipeline}
#| code-summary: Run the main pipeline
#| eval: false

source(here("src", "run_farmruns_pipeline.R"))
```

Collate the pipeline objects.

- The only purpose of `fish_ends` is for variance partitioning
- `farm_ends` is the read output

```{r save-fish-ends-results}
#| code-summary: Save fish_ends objects as files

fish_ends_files <- here("outputs/model_run_outputs/fish_ends") %>% 
  list.files(full.names = T, recursive = T, pattern = ".qs")

fish_ends_measures <- c("weight", "total_carbon", "total_nitrogen")

for (m in fish_ends_measures) {
  if (m == "weight") {
    fish_ends <- fish_ends_files %>% 
      map_dfr(function(fnm) {
        qread(fnm) %>% 
          filter(measure == m) %>% 
          select(-value_perbiom, -measure, -fish) %>% 
          mutate(farm_ID = as.factor(farm_ID))
      })
  } else {
    fish_ends <- fish_ends_files %>% 
      map_dfr(function(fnm) {
        qread(fnm) %>% 
          filter(measure == m) %>% 
          select(-value, -measure, -fish) %>% 
          mutate(farm_ID = as.factor(farm_ID))
      })
  }
  qsave(fish_ends, here("outputs/model_run_outputs", str_c("fish_ends_", m, ".qs")))
}

rm(fish_ends)
gc()
```

```{r save-farms-results}
#| code-summary: Save farm_ends objects as files

farm_ends_files <- here("outputs/model_run_outputs/farm_ends") %>% 
  list.files(full.names = T, recursive = T, pattern = ".qs")

farm_ends_measures <- farm_ends_files %>% 
  first() %>% qread() %>% pull(measure) %>% sort() %>% unique()

for (m in farm_ends_measures) {
  farm_ends <- farm_ends_files %>% 
    map_dfr(function(fnm) {
      qread(fnm) %>% 
        filter(measure == m) %>% 
        mutate(measure = as.factor(measure))
    })
  qsave(farm_ends, here("outputs/model_run_outputs", str_c("farm_ends_", m, ".qs")))
}

rm(farm_ends)
gc()
```

```{r save-farm-runs-results}
#| code-summary: Save farm_runs objects as files

farm_runs_files <- here("outputs/model_run_outputs/farm_runs") %>% 
  list.files(full.names = T, recursive = T, pattern = ".qs")

farm_runs_measures <- farm_runs_files %>% 
  first() %>% qread() %>% pull(measure) %>% sort() %>% unique()

for (m in farm_runs_measures) {
  farm_runs <- farm_runs_files %>% 
    map_dfr(function(fnm) {
      qread(fnm) %>% 
        filter(measure == m) %>% 
        mutate(measure = as.factor(measure), prod_t = as.integer(prod_t))
    })
  qsave(farm_runs, here("outputs/model_run_outputs", str_c("farm_runs_", m, ".qs")))
}

rm(farm_runs)
gc()
```

# Run sensitivities {#sec-run-sensitivities}

```{r check-sensitivities-pipeline}
#| code-summary: Check that the pipeline will run correctly

Sys.setenv(TAR_PROJECT = "project_sensitivities")

tar_make(test_reference_feed)
tar_read(test_reference_feed) # if weight < 1000g then feeds aren't processing properly! Fix it!
```

```{r run-sensitivities-pipeline}
#| code-summary: "Run the full sensitivities pipeline"

Sys.setenv(TAR_PROJECT = "project_sensitivities")

# Run whole pipeline
tar_make(seconds_meta_append = 300)
```

```{r sens-results}
#| code-summary: "Load and save sensitivity analysis results"

tar_load(sens_results_pop)
tar_load(sens_results_spec)

sens <- rbind(sens_results_pop, sens_results_spec)
qsave(sens, file.path(output_sens_data_path, "sens_all.qs"))
```

[Next: Data analysis →](09_data_analysis.qmd)
